server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka

spring:
  application:
    name: rollin-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-origins:
              - "http://localhost:3000"
            allowed-headers: "*"
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - CustomFilter

        - id: paper-service
          uri: lb://PAPER-SERVICE
          predicates:
            - Path=/paper/**
          filters:
            - CustomFilter
            - AuthFilter

        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path= /board/**,/upload
          filters:
            - CustomFilter
            - AuthFilter

        - id: gift-service
          uri: lb://GIFT-SERVICE
          predicates:
            - Path=/gift/**, /mail/**
          filters:
            - CustomFilter
            - AuthFilter
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace